package com.aliyun.playerkit.event;

import androidx.annotation.NonNull;

/**
 * AliPlayerKit 插槽事件定义
 * <p>
 * 定义了插槽内部产生的事件类型，用于插槽与组件之间的通信。
 * 所有插槽事件都继承自 {@link PlayerEvent}，可以通过事件总线订阅。
 * </p>
 * <p>
 * AliPlayerKit Slot Events Definition
 * <p>
 * Defines event types generated by slots, used for communication between slots and components.
 * All slot events extend from {@link PlayerEvent} and can be subscribed through the event bus.
 * </p>
 *
 * @author keria
 * @date 2025/11/21
 */
public final class SlotEvents {

    private SlotEvents() {
        throw new UnsupportedOperationException("Cannot instantiate SlotEvents");
    }

    /**
     * 顶部栏返回按钮点击事件
     * <p>
     * Top Bar Back Button Clicked Event
     * </p>
     */
    public static final class TopBarBackClicked extends PlayerEvent {
        public TopBarBackClicked(@NonNull String playerId) {
            super(playerId);
        }
    }
}
