package com.aliyun.playerkit.data;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.io.Serializable;
import java.util.List;

/**
 * 章节信息
 * <p>
 * 表示视频中的一个章节，包含时间范围和标题。
 * 通常由视频拆条（将长视频按内容/语义拆分为多个片段）后生成，
 * 用于 AI_VOD 场景下，BottomBarSlot 在进度条上绘制章节标记点，
 * 以及用户 Seek 时显示当前章节信息。
 * </p>
 * <p>
 * Chapter Info
 * <p>
 * Represents a chapter in the video with time range and title.
 * Typically generated by video segmentation (splitting a long video
 * into multiple segments based on content/semantics).
 * Used in AI_VOD scene for drawing chapter markers on the progress bar
 * and displaying chapter info during seek.
 * </p>
 *
 * @author keria
 * @date 2026/07/03
 */
public class ChapterInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 章节唯一标识（可选）
     * <p>
     * 用于 AI 场景下后端数据关联，非 AI 场景可为 null。
     * </p>
     * <p>
     * Optional chapter ID for backend data association in AI scenarios.
     * </p>
     */
    @Nullable
    private final String id;

    /**
     * 章节开始时间，单位毫秒
     * <p>
     * Chapter start time in milliseconds
     */
    private final long startMs;

    /**
     * 章节结束时间，单位毫秒
     * <p>
     * Chapter end time in milliseconds
     */
    private final long endMs;

    /**
     * 章节标题
     * <p>
     * Chapter title
     */
    @NonNull
    private final String title;

    /**
     * 章节缩略图 URL
     * <p>
     * Chapter thumbnail URL
     */
    @Nullable
    private final String thumbnailUrl;

    /**
     * Gson 反序列化专用
     */
    @SuppressWarnings("unused")
    private ChapterInfo() {
        this(null, 0, 0, "", null);
    }

    /**
     * 构造函数
     * <p>
     * Constructor
     * </p>
     *
     * @param startMs 章节开始时间，单位毫秒
     * @param endMs   章节结束时间，单位毫秒
     * @param title   章节标题
     */
    public ChapterInfo(long startMs, long endMs, @NonNull String title) {
        this(startMs, endMs, title, null);
    }

    /**
     * 构造函数
     * <p>
     * Constructor
     * </p>
     *
     * @param startMs      章节开始时间，单位毫秒
     * @param endMs        章节结束时间，单位毫秒
     * @param title        章节标题
     * @param thumbnailUrl 章节缩略图 URL
     */
    public ChapterInfo(long startMs, long endMs, @NonNull String title, @Nullable String thumbnailUrl) {
        this(null, startMs, endMs, title, thumbnailUrl);
    }

    /**
     * 构造函数（含 ID）
     * <p>
     * Constructor with ID
     * </p>
     *
     * @param id           章节唯一标识
     * @param startMs      章节开始时间，单位毫秒
     * @param endMs        章节结束时间，单位毫秒
     * @param title        章节标题
     * @param thumbnailUrl 章节缩略图 URL
     */
    public ChapterInfo(@Nullable String id, long startMs, long endMs, @NonNull String title, @Nullable String thumbnailUrl) {
        if (startMs < 0) {
            throw new IllegalArgumentException("startMs must be non-negative, got: " + startMs);
        }
        if (endMs < startMs) {
            throw new IllegalArgumentException("endMs must be >= startMs, got startMs=" + startMs + ", endMs=" + endMs);
        }
        this.id = id;
        this.startMs = startMs;
        this.endMs = endMs;
        this.title = title;
        this.thumbnailUrl = thumbnailUrl;
    }

    /**
     * 获取章节唯一标识
     * <p>
     * Get chapter ID (nullable, only available in AI scenarios)
     * </p>
     *
     * @return 章节唯一标识，非 AI 场景为 null
     */
    @Nullable
    public String getId() {
        return id;
    }

    /**
     * 获取章节开始时间
     * <p>
     * Get chapter start time
     * </p>
     *
     * @return 章节开始时间，单位毫秒
     */
    public long getStartMs() {
        return startMs;
    }

    /**
     * 获取章节结束时间
     * <p>
     * Get chapter end time
     * </p>
     *
     * @return 章节结束时间，单位毫秒
     */
    public long getEndMs() {
        return endMs;
    }

    /**
     * 获取章节标题
     * <p>
     * Get chapter title
     * </p>
     *
     * @return 章节标题
     */
    @NonNull
    public String getTitle() {
        return title;
    }

    /**
     * 获取章节缩略图 URL
     * <p>
     * Get chapter thumbnail URL
     * </p>
     *
     * @return 章节缩略图 URL
     */
    @Nullable
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * 根据播放位置查找当前章节索引（二分查找，O(log n)）
     * <p>
     * 假定章节列表按时间范围有序排列。
     * </p>
     * <p>
     * Find chapter index by playback position using binary search (O(log n)).
     * Assumes chapters are sorted by time range.
     * </p>
     *
     * @param chapters   章节列表
     * @param positionMs 当前播放位置（毫秒）
     * @return 当前章节索引，未找到返回 -1
     */
    public static int findIndexByPosition(@Nullable List<ChapterInfo> chapters, long positionMs) {
        if (chapters == null || chapters.isEmpty()) return -1;

        int low = 0;
        int high = chapters.size() - 1;

        while (low <= high) {
            int mid = (low + high) >>> 1;
            ChapterInfo chapter = chapters.get(mid);
            if (positionMs < chapter.startMs) {
                high = mid - 1;
            } else if (positionMs >= chapter.endMs) {
                low = mid + 1;
            } else {
                return mid;
            }
        }
        return -1;
    }

    /**
     * 返回章节信息的字符串表示
     * <p>
     * Return the string representation of the chapter info
     * </p>
     *
     * @return 章节信息字符串
     */
    @NonNull
    @Override
    public String toString() {
        return "ChapterInfo{" +
                "id='" + id + '\'' +
                ", startMs=" + startMs +
                ", endMs=" + endMs +
                ", title='" + title + '\'' +
                ", thumbnailUrl='" + thumbnailUrl + '\'' +
                '}';
    }
}
